### ISSUE TITLE
Bug: FastAPILimiter cannot be imported in v0.2.0 — __init__.py is empty

### ISSUE THREAD

**Issue by bnawras** [long2ice/fastapi-limiter#78]
@long2ice 

After upgrading to v0.2.0, importing FastAPILimiter raises an ImportError. This is caused by [commit ae102cf](https://github.com/long2ice/fastapi-limiter/commit/ae102cf1e768308cf83a7b9f5922ca33e19760c9), which cleared the contents of `__init__.py`

**Comment by jayhsia1997** [comment]
It seems that v0.2.0 has changed the rate limiter mechanism, moving away from using Redis for counter storage and instead using pyrate-limiter for rate limiting. However, the development team hasn’t explained the reason for this change.

**Comment by AdityaMedidala** [comment]
Confirmed on Python 3.12.2 with fastapi-limiter==0.2.0.

Running from fastapi_limiter import FastAPILimiter raises:
ImportError: cannot import name 'FastAPILimiter'

Root cause appears to be that fastapi_limiter/__init__.py no longer re-exports FastAPILimiter.

Happy to submit a PR once expected behavior is confirmed (restore re-export vs document new import path).
